### ISSUE TITLE
Contact form alternative using Google Forms

### ISSUE THREAD

**Issue by emmahsax** [Joello24/Joello24.github.io#1]
Hi @Joello24.

I saw that your website's contact form doesn't really work (or works locally), as GitHub Pages only allows static files. I also run my website on GitHub Pages, and found a workaround using Google Forms. This allowed me to have a complete contact form and I can receive emails about when there are new submissions, without having to change my hosting platform (AKA keeping my website free!).

If you're interested, I wrote a blog post about it: https://emmasax.com/blog/posts/adding-html-forms-to-static-sites/

**Comment by Joello24** [comment]
Interesting, I checked out your blog, I'm out of town but I'll definitely look further into this and implement this when I get home. Thanks!

**Comment by emmahsax** [comment]
@Joello24 I am going to close out this issue. You certainly don't need to implement what I did, it was just an idea, and since I've brought it up, the purpose of my issue has been met!
